# imagem leve com node
FROM node:20-alpine

# diretório de trabalho
WORKDIR /app

# copia dependências primeiro (cache)
COPY package*.json ./

RUN npm install

# copia o resto do projeto
COPY . .

# Vite precisa expor para fora do container
EXPOSE 5173

# roda o dev server acessível externamente
CMD ["npm", "run", "dev", "--", "--host"]
